// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmqfviewtrplbzwlyzwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcWZ2aWV3dHJwbGJ6d2x5enduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0Njc4NjYsImV4cCI6MjA3MjA0Mzg2Nn0.Yn9ZarKFEvlbVSOBRW7WvLDuCrAXH4zHdr5hr07ivv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});